<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Aegis.Payroll.Domain/Aegis.Payroll.Domain.csproj" />
    <ProjectReference Include="../Aegis.Payroll.Infrastructure/Aegis.Payroll.Infrastructure.csproj" />
  </ItemGroup>
</Project>
